<?php
require_once("class_user.php");
require_once("class_theme.php");
require_once("class_article.php");
require_once("class_comment.php");
require_once("class_enregistre.php");
require_once("class_file.php");
require_once("class_sujet.php");
require_once("class_reponse.php");