<?php
require_once("homeController.php");
require_once("userController.php");
require_once("themeController.php");
require_once("articleController.php");
require_once("commentaireController.php");
require_once("enregistreController.php");
require_once("emailController.php");
require_once("sujetController.php");
require_once("reponseController.php");